name: CorpX Deploy Workflow

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "!.gitignore"
      - "!README.md"
      - "!CONTRIBUTING.md"
      - "!LICENSE"

  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Lint everything
        run: npm run lint:all

      - name: Run custom scripts
        env:
          URL_CHECKER_TIMEOUT: ${{ vars.URL_CHECKER_TIMEOUT }}
        run: |
          node script/url-checker.js -t $URL_CHECKER_TIMEOUT
